### ISSUE TITLE
Jetbrains.Annotations namespace is duplicated after applying changes

### ISSUE THREAD

**Issue by imanushin** [bkoelman/ResharperCodeContractNullability#16] opened 2016-01-24 12:04 UTC
Steps to reproduce:
1. Open file with Jetbrains.Annotations namespace declared
2. Apply code fix for the one of the function arguments
3. Check the namespaces

Before:
```
using JetBrains.Annotations;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using CheckContracts;
```

After:
```
using JetBrains.Annotations;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using CheckContracts;
using JetBrains.Annotations; //duplicated !!!
```

**Comment by bkoelman** [comment] 2016-01-24 14:52
Thanks for reporting this. However I cannot reproduce with the steps above. It would help if you could attach a sample project.

**Comment by imanushin** [comment] 2016-02-14 21:24
1. Download [project](https://github.com/imanushin/ColorsMagic)
2. Open [file](https://github.com/imanushin/ColorsMagic/blob/master/Source/ColorsMagic/ColorsMagic.Common/GameModel/GridGenerator.cs) in MSVS
3. Go to line 18, to argument "PortableSize maxSize"
4. Press Ctrl-'.'
5. Select "Add NotNull"
6. Apply
7. Check the namespaces

Before:
```
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using CheckContracts;
using JetBrains.Annotations;
```

Expected after:
```
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using CheckContracts;
using JetBrains.Annotations;
```

Actual after:
```
using JetBrains.Annotations; // <--- this line was added after the code fix
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using CheckContracts;
using JetBrains.Annotations;
```

**Comment by bkoelman** [comment] 2016-05-19 21:50
@imanushin The [related fix](https://github.com/dotnet/roslyn/pull/9229) in roslyn has been merged. This should light up in the next VS release.

**Closed by bkoelman** 2016-05-19 21:50 UTC
